version: '3.8'

services:

    micro_getway:
        build:
            args:
                user: leandro
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - microgetway

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8003:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d
        networks:
            - microgetway

networks:
    microgetway:
        driver: bridge
